=== almogrc/GPUP_Client_Server/out/production/LOGIC/resources/G.P.U.P-V3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="GPUP-Working-Directory" type="xs:string"/>
	<xs:element name="GPUP-User-Data" type="xs:string"/>
	<xs:element name="GPUP-Targets">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GPUP-Target" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GPUP-Target-Dependencies">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="GPUG-Dependency" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="type" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="requiredFor"/>
											<xs:enumeration value="dependsOn"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GPUP-Target">
		<xs:complexType>
			<xs:all>
				<xs:element ref="GPUP-User-Data" minOccurs="0"/>
				<xs:element ref="GPUP-Target-Dependencies" minOccurs="0"/>
			</xs:all>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="GPUP-Graph-Name" type="xs:string"/>
	<xs:element name="GPUP-Descriptor">
		<xs:complexType>
			<xs:all>
				<xs:element ref="GPUP-Configuration"/>
				<xs:element ref="GPUP-Targets"/>
				<xs:element name="GPUP-Serial-Sets" minOccurs="0">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="GPUP-Serial-set">
								<xs:complexType>
									<xs:attribute name="targets" type="xs:string" use="required"/>
									<xs:attribute name="name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="GPUP-Configuration">
		<xs:complexType>
			<xs:all>
				<xs:element ref="GPUP-Graph-Name"/>
				<xs:element name="GPUP-Pricing">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="GPUP-Task" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="Simulation"/>
												<xs:enumeration value="Compilation"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="price-per-target" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== almogrc/GPUP_Client_Server/XML test files/ex3-small.xml
<GPUP-Descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="G.P.U.P-V3.xsd">
	<GPUP-Configuration>
		<GPUP-Graph-Name>Test</GPUP-Graph-Name>
		<GPUP-Pricing>
			<GPUP-Task name="Simulation" price-per-target="5"/>
		</GPUP-Pricing>
	</GPUP-Configuration>
	<GPUP-Targets>
		<GPUP-Target name="A">
			<GPUP-User-Data>freeText</GPUP-User-Data>
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="requiredFor">D</GPUG-Dependency>
			</GPUP-Target-Dependencies>			
		</GPUP-Target>
		<GPUP-Target name="B">			
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="requiredFor">D</GPUG-Dependency>
				<GPUG-Dependency type="requiredFor">E</GPUG-Dependency>
			</GPUP-Target-Dependencies>
		</GPUP-Target>
		<GPUP-Target name="C">
			<GPUP-User-Data>freeText</GPUP-User-Data>
		</GPUP-Target>
		<GPUP-Target name="D">
			<GPUP-User-Data>freeText</GPUP-User-Data>
		</GPUP-Target>
		<GPUP-Target name="E">
			<GPUP-User-Data>freeText</GPUP-User-Data>
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="dependsOn">D</GPUG-Dependency>
				<GPUG-Dependency type="dependsOn">C</GPUG-Dependency>
			</GPUP-Target-Dependencies>
		</GPUP-Target>
	</GPUP-Targets>
</GPUP-Descriptor>

=== almogrc/GPUP_Client_Server/XML test files/ex3-compilation.xml
<GPUP-Descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="G.P.U.P-V3.xsd">
	<GPUP-Configuration>
		<GPUP-Graph-Name>XOO Example Java Project</GPUP-Graph-Name>
		<GPUP-Pricing>
			<GPUP-Task name="Simulation" price-per-target="5"/>
			<GPUP-Task name="Compilation" price-per-target="15"/>
		</GPUP-Pricing>
	</GPUP-Configuration>
	<GPUP-Targets>
		<GPUP-Target name="ZOO">
			<GPUP-User-Data>gpup.compilation.example.l3.Zoo</GPUP-User-Data>
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="dependsOn">DOO</GPUG-Dependency>
			</GPUP-Target-Dependencies>			
		</GPUP-Target>
		<GPUP-Target name="POO">
			<GPUP-User-Data>gpup.compilation.example.l3.Poo</GPUP-User-Data>
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="dependsOn">MOO</GPUG-Dependency>
			</GPUP-Target-Dependencies>			
		</GPUP-Target>	
		<GPUP-Target name="NOO">
			<GPUP-User-Data>gpup.compilation.example.l3.Noo</GPUP-User-Data>
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="dependsOn">FOO</GPUG-Dependency>
			</GPUP-Target-Dependencies>			
		</GPUP-Target>	
		<GPUP-Target name="LOO">
			<GPUP-User-Data>gpup.compilation.example.l3.Loo</GPUP-User-Data>
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="dependsOn">GOO</GPUG-Dependency>
				<GPUG-Dependency type="dependsOn">KOO</GPUG-Dependency>				
			</GPUP-Target-Dependencies>			
		</GPUP-Target>
		<GPUP-Target name="KOO">
			<GPUP-User-Data>gpup.compilation.example.l2.Koo</GPUP-User-Data>				
		</GPUP-Target>	
		<GPUP-Target name="GOO">
			<GPUP-User-Data>gpup.compilation.example.l2.Goo</GPUP-User-Data>
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="dependsOn">MOO</GPUG-Dependency>				
			</GPUP-Target-Dependencies>			
		</GPUP-Target>
		<GPUP-Target name="DOO">
			<GPUP-User-Data>gpup.compilation.example.l2.Doo</GPUP-User-Data>
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="dependsOn">FOO</GPUG-Dependency>				
			</GPUP-Target-Dependencies>			
		</GPUP-Target>
		<GPUP-Target name="MOO">
			<GPUP-User-Data>gpup.compilation.example.l1.Moo</GPUP-User-Data>				
		</GPUP-Target>	
		<GPUP-Target name="FOO">
			<GPUP-User-Data>gpup.compilation.example.l1.Foo</GPUP-User-Data>			
		</GPUP-Target>	
		<GPUP-Target name="BOO">
			<GPUP-User-Data>gpup.compilation.example.l1.Boo</GPUP-User-Data>				
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="requiredFor">FOO</GPUG-Dependency>
				<GPUG-Dependency type="requiredFor">DOO</GPUG-Dependency>
				<GPUG-Dependency type="requiredFor">GOO</GPUG-Dependency>
				<GPUG-Dependency type="requiredFor">ZOO</GPUG-Dependency>								
			</GPUP-Target-Dependencies>						
		</GPUP-Target>											
	</GPUP-Targets>
</GPUP-Descriptor>
