=== almogrc/GPUP_Client_Server/out/production/LOGIC/resources/G.P.U.P-V1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="GPUP-Working-Directory" type="xs:string"/>
	<xs:element name="GPUP-User-Data" type="xs:string"/>
	<xs:element name="GPUP-Targets">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GPUP-Target" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GPUP-Target-Dependencies">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="GPUG-Dependency" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="type" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="requiredFor"/>
											<xs:enumeration value="dependsOn"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GPUP-Target">
		<xs:complexType>
			<xs:all>
				<xs:element ref="GPUP-User-Data" minOccurs="0"/>
				<xs:element ref="GPUP-Target-Dependencies" minOccurs="0"/>
			</xs:all>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="GPUP-Graph-Name" type="xs:string"/>
	<xs:element name="GPUP-Descriptor">
		<xs:complexType>
			<xs:all>
				<xs:element ref="GPUP-Configuration"/>
				<xs:element ref="GPUP-Targets"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="GPUP-Configuration">
		<xs:complexType>
			<xs:all>
				<xs:element ref="GPUP-Graph-Name"/>
				<xs:element ref="GPUP-Working-Directory"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== almogrc/GPUP_Client_Server/out/production/LOGIC/resources/ex1-big(1).xml
<GPUP-Descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="G.P.U.P-V1.xsd">
	<GPUP-Configuration>
		<GPUP-Graph-Name>Womans Gradle</GPUP-Graph-Name>
		<GPUP-Working-Directory>c:\temp</GPUP-Working-Directory>
	</GPUP-Configuration>
	<GPUP-Targets>
		<GPUP-Target name="A">
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="dependsOn">L</GPUG-Dependency>																
			</GPUP-Target-Dependencies>		
		</GPUP-Target>
		<GPUP-Target name="B"/>
		<GPUP-Target name="C"/>
		<GPUP-Target name="D"/>
		<GPUP-Target name="E"/>						
		<GPUP-Target name="K"/>						
		<GPUP-Target name="L"/>						
		<GPUP-Target name="M"/>						
		<GPUP-Target name="N"/>						
		<GPUP-Target name="O"/>						
		<GPUP-Target name="P"/>						
		<GPUP-Target name="Q"/>						
		<GPUP-Target name="R"/>																						
		<GPUP-Target name="F">
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="requiredFor">A</GPUG-Dependency>
				<GPUG-Dependency type="requiredFor">B</GPUG-Dependency>				
				<GPUG-Dependency type="requiredFor">C</GPUG-Dependency>				
				<GPUG-Dependency type="dependsOn">H</GPUG-Dependency>																
			</GPUP-Target-Dependencies>
		</GPUP-Target>
		<GPUP-Target name="G">
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="requiredFor">C</GPUG-Dependency>
				<GPUG-Dependency type="requiredFor">D</GPUG-Dependency>
			</GPUP-Target-Dependencies>
		</GPUP-Target>
		<GPUP-Target name="H">
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="requiredFor">B</GPUG-Dependency>
				<GPUG-Dependency type="requiredFor">F</GPUG-Dependency>				
				<GPUG-Dependency type="dependsOn">K</GPUG-Dependency>												
				<GPUG-Dependency type="dependsOn">L</GPUG-Dependency>												
				<GPUG-Dependency type="dependsOn">M</GPUG-Dependency>																				
			</GPUP-Target-Dependencies>
		</GPUP-Target>
		<GPUP-Target name="I">
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="requiredFor">C</GPUG-Dependency>
				<GPUG-Dependency type="requiredFor">E</GPUG-Dependency>				
				<GPUG-Dependency type="dependsOn">L</GPUG-Dependency>												
				<GPUG-Dependency type="dependsOn">M</GPUG-Dependency>												
				<GPUG-Dependency type="dependsOn">N</GPUG-Dependency>																				
			</GPUP-Target-Dependencies>
		</GPUP-Target>
		<GPUP-Target name="J">
			<GPUP-Target-Dependencies>
				<GPUG-Dependency type="requiredFor">D</GPUG-Dependency>
				<GPUG-Dependency type="requiredFor">E</GPUG-Dependency>				
				<GPUG-Dependency type="dependsOn">N</GPUG-Dependency>								
				<GPUG-Dependency type="dependsOn">O</GPUG-Dependency>								
				<GPUG-Dependency type="dependsOn">P</GPUG-Dependency>																
			</GPUP-Target-Dependencies>
		</GPUP-Target>		
	</GPUP-Targets>
</GPUP-Descriptor>
